apps:
  - name: sample-app-test
    image:
      repository: kiranyn/app1
      tag: latest
      pullPolicy: IfNotPresent
    containerPort: 3000
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      host: app1.kubeace.com
      tlsSecret: sample-app1-tl

  - name: sample-app2-test
    image:
      repository: kiranyn/app2
      tag: latest
      pullPolicy: IfNotPresent
    containerPort: 80
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      host: app2.kubeace.com
      tlsSecret: sample-app2-tl
