apps:
  - name: sample-app
    image:
      repository: kiranyn/app1
      tag: latest
      pullPolicy: IfNotPresent
    containerPort: 3000
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: app1.kubeace.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - app1.kubeace.com
          secretName: sample-app-tls

  - name: sample-app2
    image:
      repository: kiranyn/app2
      tag: latest
      pullPolicy: IfNotPresent
    containerPort: 80
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: app2.kubeace.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - app2.kubeace.com
          secretName: sample-app2-tls
