{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .containerPort }}
---
{{- end }}

