{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .containerPort }}
  type: ClusterIP
---
{{- end }}
